# Generated by Django 5.1.4 on 2024-12-19 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PartPrefix",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prefix", models.CharField(max_length=8, verbose_name="PREFIX")),
            ],
        ),
        migrations.CreateModel(
            name="PartSuffix",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("suffix", models.CharField(max_length=8, verbose_name="SUFFIX")),
            ],
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="NAME")),
                ("address", models.CharField(max_length=75, verbose_name="ADDRESS")),
                ("country", models.CharField(max_length=50, verbose_name="COUNTRY")),
                (
                    "approved",
                    models.BooleanField(
                        default=False, verbose_name="APPROVED_SUPPLIER"
                    ),
                ),
                (
                    "supplier_class",
                    models.CharField(max_length=10, verbose_name="SUPPLIER_CLASS"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PartNumberSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("middle", models.CharField(max_length=10, verbose_name="MIDDLE")),
                ("spacer", models.CharField(max_length=2, verbose_name="SPACER")),
                (
                    "prefix",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Material.partprefix",
                    ),
                ),
                (
                    "suffix",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Material.partsuffix",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Parts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("partname", models.CharField(max_length=50, verbose_name="PART_NAME")),
                (
                    "description",
                    models.CharField(max_length=100, verbose_name="DESCRIPTION"),
                ),
                (
                    "partnumber",
                    models.CharField(max_length=30, verbose_name="PART_NUMBER"),
                ),
                (
                    "inspection",
                    models.BooleanField(
                        default=False, verbose_name="INSPECTION_REQUIRED"
                    ),
                ),
                (
                    "partnumberstyle",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Material.partnumbersequence",
                    ),
                ),
                (
                    "supplier",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Material.supplier",
                    ),
                ),
            ],
        ),
    ]
