# Generated by Django 5.1.4 on 2024-12-19 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Material", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordergroup",
            name="groupordernumber",
            field=models.CharField(
                default="1GD7FADGCB",
                max_length=10,
                null=True,
                verbose_name="GROUP_ORDER_NUMBER",
            ),
        ),
        migrations.AddField(
            model_name="orders",
            name="order_number",
            field=models.CharField(
                blank=True,
                default="G0C1G1ECEF",
                max_length=10,
                null=True,
                verbose_name="ORDER_NUMBER",
            ),
        ),
        migrations.AddField(
            model_name="parts",
            name="lot_serial_number",
            field=models.CharField(
                blank=True, max_length=6, null=True, verbose_name="LOT_SERIAL_NUMBER"
            ),
        ),
        migrations.CreateModel(
            name="SerialNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="SERIAL_NUMBER",
                    ),
                ),
                (
                    "date_generated",
                    models.DateField(
                        blank=True, null=True, verbose_name="DATE_GENERATED"
                    ),
                ),
                (
                    "lot_number",
                    models.CharField(
                        blank=True, max_length=6, null=True, verbose_name="LOT_NUMBER"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, max_length=250, null=True, verbose_name="NOTES"
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Material.parts",
                    ),
                ),
            ],
        ),
    ]
