# Generated by Django 5.1.4 on 2024-12-19 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Material", "0002_ordergroup_groupordernumber_orders_order_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordergroup",
            name="groupordernumber",
            field=models.CharField(
                default="EB9ABA203A",
                max_length=10,
                null=True,
                verbose_name="GROUP_ORDER_NUMBER",
            ),
        ),
        migrations.AlterField(
            model_name="orders",
            name="order_number",
            field=models.CharField(
                blank=True,
                default="F9B6GB053C",
                max_length=10,
                null=True,
                verbose_name="ORDER_NUMBER",
            ),
        ),
    ]
