# Generated by Django 5.1.4 on 2024-12-19 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Material", "0003_alter_ordergroup_groupordernumber_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordergroup",
            name="groupordernumber",
            field=models.CharField(
                default="608240ACC1",
                max_length=10,
                null=True,
                verbose_name="GROUP_ORDER_NUMBER",
            ),
        ),
        migrations.AlterField(
            model_name="orders",
            name="order_number",
            field=models.CharField(
                blank=True,
                default="GG028D28A7",
                max_length=10,
                null=True,
                verbose_name="ORDER_NUMBER",
            ),
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="QUANTITY",
                    ),
                ),
                (
                    "date",
                    models.DateField(blank=True, null=True, verbose_name="DATE_ADDED"),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, max_length=250, null=True, verbose_name="NOTES"
                    ),
                ),
                (
                    "description",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="PART_DESCRIPTION",
                        to="Material.parts",
                    ),
                ),
                (
                    "identifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Material.serialnumber",
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="PART_NUMBER",
                        to="Material.parts",
                    ),
                ),
            ],
        ),
    ]
