# Generated by Django 5.1.4 on 2024-12-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Material", "0004_alter_ordergroup_groupordernumber_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordergroup",
            name="groupordernumber",
            field=models.CharField(
                default="1FA3EC3C49",
                max_length=10,
                null=True,
                verbose_name="GROUP_ORDER_NUMBER",
            ),
        ),
        migrations.AlterField(
            model_name="orders",
            name="order_number",
            field=models.CharField(
                blank=True,
                default="3E07DGB29E",
                max_length=10,
                null=True,
                verbose_name="ORDER_NUMBER",
            ),
        ),
    ]
