# Generated by Django 5.1.4 on 2024-12-19 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Material", "0008_orders_part10_orders_part10_due_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordergroup",
            name="groupordernumber",
            field=models.CharField(
                default="CE13CE532G",
                max_length=10,
                null=True,
                verbose_name="GROUP_ORDER_NUMBER",
            ),
        ),
        migrations.AlterField(
            model_name="orders",
            name="order_number",
            field=models.CharField(
                blank=True,
                default="A17G922G25",
                max_length=10,
                null=True,
                verbose_name="ORDER_NUMBER",
            ),
        ),
        migrations.AlterField(
            model_name="partnumbersequence",
            name="middle",
            field=models.IntegerField(
                blank=True, max_length=10, null=True, verbose_name="MIDDLE"
            ),
        ),
    ]
