# Generated by Django 5.1.4 on 2024-12-19 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Material", "0009_alter_ordergroup_groupordernumber_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordergroup",
            name="groupordernumber",
            field=models.CharField(
                default="A11C5644B4",
                max_length=10,
                null=True,
                verbose_name="GROUP_ORDER_NUMBER",
            ),
        ),
        migrations.AlterField(
            model_name="orders",
            name="order_number",
            field=models.CharField(
                blank=True,
                default="54GAE1EDA2",
                max_length=10,
                null=True,
                verbose_name="ORDER_NUMBER",
            ),
        ),
        migrations.AlterField(
            model_name="partnumbersequence",
            name="middle",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="MIDDLE"
            ),
        ),
    ]
