# Generated by Django 5.1.4 on 2024-12-19 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Material", "0010_alter_ordergroup_groupordernumber_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordergroup",
            name="groupordernumber",
            field=models.CharField(
                default="71G51GF12C",
                max_length=10,
                null=True,
                verbose_name="GROUP_ORDER_NUMBER",
            ),
        ),
        migrations.AlterField(
            model_name="orders",
            name="order_number",
            field=models.CharField(
                blank=True,
                default="9144BAD018",
                max_length=10,
                null=True,
                verbose_name="ORDER_NUMBER",
            ),
        ),
    ]
