# Generated by Django 5.1.4 on 2024-12-20 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Material", "0013_alter_ordergroup_groupordernumber_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="city",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="CITY"
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="email",
            field=models.EmailField(
                blank=True, max_length=50, null=True, verbose_name="EMAIL"
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=25, null=True, verbose_name="PHONE_NUMBER"
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="state",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="STATE"
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="website",
            field=models.URLField(
                blank=True, max_length=50, null=True, verbose_name="WEBSITE"
            ),
        ),
        migrations.AlterField(
            model_name="ordergroup",
            name="groupordernumber",
            field=models.CharField(
                default="961B2A847F",
                max_length=10,
                null=True,
                verbose_name="GROUP_ORDER_NUMBER",
            ),
        ),
        migrations.AlterField(
            model_name="orders",
            name="order_number",
            field=models.CharField(
                blank=True,
                default="0A43D7F875",
                max_length=10,
                null=True,
                verbose_name="ORDER_NUMBER",
            ),
        ),
    ]
