# Generated by Django 5.1.4 on 2024-12-20 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Material",
            "0014_supplier_city_supplier_email_supplier_phone_number_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplierClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "class_type",
                    models.TextField(
                        blank=True, max_length=6, null=True, verbose_name="CLASS_TYPE"
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="ordergroup",
            name="groupordernumber",
            field=models.CharField(
                default="0DDBD35A15",
                max_length=10,
                null=True,
                verbose_name="GROUP_ORDER_NUMBER",
            ),
        ),
        migrations.AlterField(
            model_name="orders",
            name="order_number",
            field=models.CharField(
                blank=True,
                default="C9G809E6BE",
                max_length=10,
                null=True,
                verbose_name="ORDER_NUMBER",
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="supplier_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Material.supplierclass",
            ),
        ),
    ]
