# Generated by Django 5.1.4 on 2024-12-20 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Material", "0015_supplierclass_alter_ordergroup_groupordernumber_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="approved_by",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="APPROVED_BY"
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="approved_date",
            field=models.DateField(blank=True, null=True, verbose_name="APPROVED_DATE"),
        ),
        migrations.AddField(
            model_name="supplier",
            name="approved_notes",
            field=models.TextField(
                blank=True, max_length=250, null=True, verbose_name="APPROVED_NOTES"
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="zip",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="ZIP"
            ),
        ),
        migrations.AlterField(
            model_name="ordergroup",
            name="groupordernumber",
            field=models.CharField(
                default="6AC29E59C8",
                max_length=10,
                null=True,
                verbose_name="GROUP_ORDER_NUMBER",
            ),
        ),
        migrations.AlterField(
            model_name="orders",
            name="order_number",
            field=models.CharField(
                blank=True,
                default="FF096EEC86",
                max_length=10,
                null=True,
                verbose_name="ORDER_NUMBER",
            ),
        ),
    ]
