# Generated by Django 5.1.4 on 2024-12-20 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Material", "0016_supplier_approved_by_supplier_approved_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplierclass",
            name="description",
            field=models.TextField(
                blank=True, max_length=50, null=True, verbose_name="DESCRIPTION"
            ),
        ),
        migrations.AlterField(
            model_name="ordergroup",
            name="groupordernumber",
            field=models.CharField(
                default="C5350G1A94",
                max_length=10,
                null=True,
                verbose_name="GROUP_ORDER_NUMBER",
            ),
        ),
        migrations.AlterField(
            model_name="orders",
            name="order_number",
            field=models.CharField(
                blank=True,
                default="4F2D1B0894",
                max_length=10,
                null=True,
                verbose_name="ORDER_NUMBER",
            ),
        ),
    ]
