# Generated by Django 5.1.4 on 2024-12-20 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Material", "0017_supplierclass_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnumbersequence",
            name="description",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="DESCRIPTION"
            ),
        ),
        migrations.AlterField(
            model_name="ordergroup",
            name="groupordernumber",
            field=models.CharField(
                default="831AD74956",
                max_length=10,
                null=True,
                verbose_name="GROUP_ORDER_NUMBER",
            ),
        ),
        migrations.AlterField(
            model_name="orders",
            name="order_number",
            field=models.CharField(
                blank=True,
                default="A931F603D9",
                max_length=10,
                null=True,
                verbose_name="ORDER_NUMBER",
            ),
        ),
        migrations.AlterField(
            model_name="supplierclass",
            name="description",
            field=models.TextField(
                blank=True, max_length=150, null=True, verbose_name="DESCRIPTION"
            ),
        ),
    ]
