# Generated by Django 5.1.4 on 2024-12-20 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Material", "0018_partnumbersequence_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="active",
            field=models.BooleanField(
                blank=True, default=True, null=True, verbose_name="ACTIVE"
            ),
        ),
        migrations.AlterField(
            model_name="ordergroup",
            name="groupordernumber",
            field=models.CharField(
                default="201922C019",
                max_length=10,
                null=True,
                verbose_name="GROUP_ORDER_NUMBER",
            ),
        ),
        migrations.AlterField(
            model_name="orders",
            name="order_number",
            field=models.CharField(
                blank=True,
                default="48A5201GC4",
                max_length=10,
                null=True,
                verbose_name="ORDER_NUMBER",
            ),
        ),
    ]
