# Generated by Django 5.1.4 on 2024-12-21 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Material", "0023_parts_revision_alter_company_company_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="associated_company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Material.company",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="project_projected_end_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="PROJECT_PROJECTED_END_DATE"
            ),
        ),
        migrations.AddField(
            model_name="projectteam",
            name="team_start_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="TEAM_START_DATE"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="company_id",
            field=models.CharField(
                blank=True,
                default="WW8YVCT8DJ",
                max_length=10,
                null=True,
                verbose_name="COMPANY_ID",
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="department_abbreviation",
            field=models.CharField(
                blank=True,
                max_length=12,
                null=True,
                verbose_name="DEPARTMENT_ABBREVIATION",
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="department_id",
            field=models.CharField(
                blank=True,
                default="J9SSKPXVED",
                max_length=10,
                null=True,
                verbose_name="DEPARTMENT_ID",
            ),
        ),
        migrations.AlterField(
            model_name="ordergroup",
            name="groupordernumber",
            field=models.CharField(
                default="760E65B0E5",
                max_length=10,
                null=True,
                verbose_name="GROUP_ORDER_NUMBER",
            ),
        ),
        migrations.AlterField(
            model_name="orders",
            name="order_number",
            field=models.CharField(
                blank=True,
                default="72CE5CG757",
                max_length=10,
                null=True,
                verbose_name="ORDER_NUMBER",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="org_id",
            field=models.CharField(
                blank=True,
                default="MB7AFTD2DP",
                max_length=10,
                null=True,
                verbose_name="ORG_ID",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_id",
            field=models.CharField(
                blank=True,
                default="FL84SGSGFV",
                max_length=10,
                null=True,
                verbose_name="PROJECT_ID",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.CharField(
                blank=True,
                default="WEMMQ8LVW8",
                max_length=10,
                null=True,
                verbose_name="USER_ID",
            ),
        ),
    ]
