# Generated by Django 5.1.4 on 2024-12-24 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Material", "0044_partclass_remove_parts_part_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="partprefix",
            name="active",
            field=models.BooleanField(
                blank=True, default=True, null=True, verbose_name="ACTIVE"
            ),
        ),
        migrations.AddField(
            model_name="partprefix",
            name="prefix_description",
            field=models.TextField(
                blank=True, max_length=150, null=True, verbose_name="DESCRIPTION"
            ),
        ),
        migrations.AddField(
            model_name="partsuffix",
            name="active",
            field=models.BooleanField(
                blank=True, default=True, null=True, verbose_name="ACTIVE"
            ),
        ),
        migrations.AddField(
            model_name="partsuffix",
            name="suffix_description",
            field=models.TextField(
                blank=True, max_length=150, null=True, verbose_name="DESCRIPTION"
            ),
        ),
        migrations.AddField(
            model_name="parttype",
            name="active",
            field=models.BooleanField(
                blank=True, default=True, null=True, verbose_name="ACTIVE"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="company_id",
            field=models.CharField(
                blank=True,
                default="BP7T6BMUQ3",
                max_length=10,
                null=True,
                unique=True,
                verbose_name="COMPANY_ID",
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="department_id",
            field=models.CharField(
                blank=True,
                default="RD4E39N0JE",
                max_length=10,
                null=True,
                verbose_name="DEPARTMENT_ID",
            ),
        ),
        migrations.AlterField(
            model_name="ordergroup",
            name="groupordernumber",
            field=models.CharField(
                default="G42GB43BFG",
                max_length=10,
                null=True,
                unique=True,
                verbose_name="GROUP_ORDER_NUMBER",
            ),
        ),
        migrations.AlterField(
            model_name="orders",
            name="order_number",
            field=models.CharField(
                blank=True,
                default="G07FDB2CDG",
                max_length=10,
                null=True,
                unique=True,
                verbose_name="ORDER_NUMBER",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="org_id",
            field=models.CharField(
                blank=True,
                default="2VQYBCX6AD",
                max_length=10,
                null=True,
                verbose_name="ORG_ID",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_id",
            field=models.CharField(
                blank=True,
                default="7QWG9VSV6U",
                max_length=10,
                null=True,
                verbose_name="PROJECT_ID",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.CharField(
                blank=True,
                default="0MKT283K1F",
                max_length=10,
                null=True,
                unique=True,
                verbose_name="USER_ID",
            ),
        ),
    ]
