# Generated by Django 5.1.4 on 2024-12-24 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Material", "0046_rename_parttype_partnumbertype_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="company_id",
            field=models.CharField(
                blank=True,
                default="1Z0N5EY5ME",
                max_length=10,
                null=True,
                unique=True,
                verbose_name="COMPANY_ID",
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="department_id",
            field=models.CharField(
                blank=True,
                default="JWXJG0KHT1",
                max_length=10,
                null=True,
                verbose_name="DEPARTMENT_ID",
            ),
        ),
        migrations.AlterField(
            model_name="ordergroup",
            name="groupordernumber",
            field=models.CharField(
                default="C9F135E3E4",
                max_length=10,
                null=True,
                unique=True,
                verbose_name="GROUP_ORDER_NUMBER",
            ),
        ),
        migrations.AlterField(
            model_name="orders",
            name="order_number",
            field=models.CharField(
                blank=True,
                default="03021CDD8B",
                max_length=10,
                null=True,
                unique=True,
                verbose_name="ORDER_NUMBER",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="org_id",
            field=models.CharField(
                blank=True,
                default="5FW1YK00CH",
                max_length=10,
                null=True,
                verbose_name="ORG_ID",
            ),
        ),
        migrations.RemoveField(
            model_name="parts",
            name="associated_project",
        ),
        migrations.AlterField(
            model_name="project",
            name="project_id",
            field=models.CharField(
                blank=True,
                default="JCZVDAU5S4",
                max_length=10,
                null=True,
                verbose_name="PROJECT_ID",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.CharField(
                blank=True,
                default="8Y13YRKJCN",
                max_length=10,
                null=True,
                unique=True,
                verbose_name="USER_ID",
            ),
        ),
        migrations.AddField(
            model_name="parts",
            name="associated_project",
            field=models.ManyToManyField(blank=True, null=True, to="Material.project"),
        ),
    ]
