# Generated by Django 5.1.4 on 2024-12-25 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Material", "0048_alter_company_company_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="company_id",
            field=models.CharField(
                blank=True,
                default="834TA9H8TN",
                max_length=10,
                null=True,
                unique=True,
                verbose_name="COMPANY_ID",
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="department_id",
            field=models.CharField(
                blank=True,
                default="JCQBEF6VZ9",
                max_length=10,
                null=True,
                verbose_name="DEPARTMENT_ID",
            ),
        ),
        migrations.AlterField(
            model_name="ordergroup",
            name="groupordernumber",
            field=models.CharField(
                default="FA53A35479",
                max_length=10,
                null=True,
                unique=True,
                verbose_name="GROUP_ORDER_NUMBER",
            ),
        ),
        migrations.AlterField(
            model_name="orders",
            name="order_number",
            field=models.CharField(
                blank=True,
                default="A423CA8098",
                max_length=10,
                null=True,
                unique=True,
                verbose_name="ORDER_NUMBER",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="org_id",
            field=models.CharField(
                blank=True,
                default="EZCY600PJ5",
                max_length=10,
                null=True,
                verbose_name="ORG_ID",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_id",
            field=models.CharField(
                blank=True,
                default="2ZX54VS5UG",
                max_length=10,
                null=True,
                verbose_name="PROJECT_ID",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NOT STARTED", "NOT STARTED"),
                    ("ON TRACk", "ON TRACK"),
                    ("OFF TRACK", "OFF TRACK"),
                    ("COMPLETED", "COMPLETED"),
                    ("CANCELLED", "CANCELLED"),
                ],
                default="NOT STARTED",
                max_length=50,
                null=True,
                verbose_name="PROJECT_STATUS",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.CharField(
                blank=True,
                default="7Y5NBL9SEF",
                max_length=10,
                null=True,
                unique=True,
                verbose_name="USER_ID",
            ),
        ),
    ]
